// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerialPort(arg1) {
  return window['go']['main']['App']['ConnectSerialPort'](arg1);
}

export function DisconnectSerialPort() {
  return window['go']['main']['App']['DisconnectSerialPort']();
}

export function GetInitialData() {
  return window['go']['main']['App']['GetInitialData']();
}

export function GetPM25History() {
  return window['go']['main']['App']['GetPM25History']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function ToggleSound(arg1) {
  return window['go']['main']['App']['ToggleSound'](arg1);
}
