// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectSerialPort(arg1:string):Promise<string>;

export function DisconnectSerialPort():Promise<string>;

export function GetInitialData():Promise<Record<string, any>>;

export function GetPM25History():Promise<Array<main.PM25Data>>;

export function ListSerialPorts():Promise<Array<string>>;

export function ToggleSound(arg1:boolean):Promise<void>;
